export interface Question {
  prompt: string
  choices: [string, string, string, string]
  correctIndex: number
  explanation: string
}

export interface PausePoint {
  timestamp: number
  hasQuestion: boolean
  question?: Question
}

/**
 * A processed video as generated by the (mock) pipeline, before it is
 * attached to a particular user's library.
 */
export interface ProcessedVideoData {
  videoId: string
  youtubeUrl: string
  title: string
  thumbnailUrl: string
  processedDate: string
  pausePoints: PausePoint[]
}

/** A processed video once it's stored in a specific user's library. */
export interface ProcessedVideo extends ProcessedVideoData {
  userId: string
}
